# version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: 
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: limonzzz/foodgram_backend:latest
    restart: always
    env_file: 
      - ./.env
    volumes:
      - static:/backend_static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: limonzzz/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
      - backend

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "3000:80"
    volumes:
      - static:/staticfiles/
      - media:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - backend
      - frontend
